# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elsym0C <- function(b, a, first, last) {
    .Call(`_dexterMST_elsym0C`, b, a, first, last)
}

elsym_submergeC <- function(g_list, range_list, routing) {
    .Call(`_dexterMST_elsym_submergeC`, g_list, range_list, routing)
}

elsym_mergeC <- function(b, a, first, last, g_list_, range_list_, mi1, mi2, routing) {
    .Call(`_dexterMST_elsym_mergeC`, b, a, first, last, g_list_, range_list_, mi1, mi2, routing)
}

E_STEP_MSC <- function(b, a, first, last, scoretab, min_scores, max_scores, routing) {
    .Call(`_dexterMST_E_STEP_MSC`, b, a, first, last, scoretab, min_scores, max_scores, routing)
}

H_STEP_MSC <- function(b, a, first, last, scoretab, min_scores, max_scores, routing) {
    .Call(`_dexterMST_H_STEP_MSC`, b, a, first, last, scoretab, min_scores, max_scores, routing)
}

sampleNRM <- function(theta, b, a, first, last) {
    .Call(`_dexterMST_sampleNRM`, theta, b, a, first, last)
}

prof_probC <- function(prob, min_scores, max_scores, gA, gB, MscA, MscB, nMod, routing) {
    invisible(.Call(`_dexterMST_prof_probC`, prob, min_scores, max_scores, gA, gB, MscA, MscB, nMod, routing))
}

